apiVersion: v1
kind: Service
metadata:
  name: ad_recording_management
  labels:
    app: ad_recording_management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ad_recording_management