apiVersion: v1
kind: Service
metadata:
  name: ad recording management
  labels:
    app: ad recording management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ad recording management