name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./ad_recording_management/pom.xml
          mvn clean package -f ./ad_reporting/pom.xml

      - name: Docker Build and push for AdRecordingManagement
        uses: docker/build-push-action@v4
        with:
          context: ./ad_recording_management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ad_recording_management:latest
            ghcr.io/${{ github.repository }}/ad_recording_management:${{ github.ref_name }}
            
      - name: Docker Build and push for AdReporting
        uses: docker/build-push-action@v4
        with:
          context: ./ad_reporting
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ad_reporting:latest
            ghcr.io/${{ github.repository }}/ad_reporting:${{ github.ref_name }}
            
