server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: ad recording management
          uri: http://localhost:8082
          predicates:
            - Path=/adRecordingManagements/**, 
        - id: ad reporting
          uri: http://localhost:8083
          predicates:
            - Path=/reportListManagements/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ad recording management
          uri: http://adRecordingManagement:8080
          predicates:
            - Path=/adRecordingManagements/**, 
        - id: ad reporting
          uri: http://adReporting:8080
          predicates:
            - Path=/reportListManagements/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
