---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad_recording_management
  labels:
    app: ad_recording_management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad_recording_management
  template:
    metadata:
      labels:
        app: ad_recording_management
    spec:
      containers:
        - name: ad_recording_management
          image: username/ad_recording_management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad_reporting
  labels:
    app: ad_reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad_reporting
  template:
    metadata:
      labels:
        app: ad_reporting
    spec:
      containers:
        - name: ad_reporting
          image: username/ad_reporting:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ad_recording_management
  labels:
    app: ad_recording_management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ad_recording_management


---


apiVersion: v1
kind: Service
metadata:
  name: ad_reporting
  labels:
    app: ad_reporting
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ad_reporting

