---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad recording management
  labels:
    app: ad recording management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad recording management
  template:
    metadata:
      labels:
        app: ad recording management
    spec:
      containers:
        - name: ad recording management
          image: username/ad recording management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad reporting
  labels:
    app: ad reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad reporting
  template:
    metadata:
      labels:
        app: ad reporting
    spec:
      containers:
        - name: ad reporting
          image: username/ad reporting:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: ad recording management
  labels:
    app: ad recording management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ad recording management


---


apiVersion: v1
kind: Service
metadata:
  name: ad reporting
  labels:
    app: ad reporting
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ad reporting

